### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by BurhanRaja** [AbhayKadam57/Ecommerce-Shopping-Website#1]
Make a documentation more user friendly. 

Write Intructions to use the project.
Add tech stack you used.
Add Images or Demo Video of your project.
Also define File structure.
Add description. In that, you can had why you build the project, what is your learning outcome and what problems did you face.

**Comment by BurhanRaja** [comment]
Assign the issue to me I will help you.

**Comment by AbhayKadam57** [comment]
@BurhanRaja, Thank you for reviewing the repo and offering help,  I appreciate it, I am currently working on revised documentation. Also, I am considering your points in the revised readme documentation. I will publish it soon. If I find difficulty I will definitely approach you.

**Comment by AbhayKadam57** [comment]
@BurhanRaja, Hi, Please check, I revised and try to improve the README.md file. Kindly review and suggest any further changes.

**Comment by AbhayKadam57** [comment]
@BurhanRaja, Hi, Please check, I revised and try to improve the README.md file. Kindly review and suggest any further changes.

**Comment by BurhanRaja** [comment]
> @BurhanRaja, Hi, Please check, I revised and try to improve the README.md file. Kindly review and suggest any further changes.

Great! Its looking good. If a new developer comes to look at your project it looks good and they understand the project easily.

**Comment by AbhayKadam57** [comment]
@BurhanRaja, Thank you so much for reviewing and suggesting. I am closing the issue now If you find any other issues in this repo. Please suggest.
